FROM golang:1.25-alpine AS fcc-helper
WORKDIR /src
COPY packages/fcc-extension/go ./go
COPY packages/fcc-extension/tools ./tools
WORKDIR /src/tools
RUN for attempt in 1 2 3; do go mod download && break; test "$attempt" = 3 && exit 1; sleep 5; done
RUN CGO_ENABLED=0 go build -trimpath -o /out/policy-app-helper ./cmd/policy-app-helper

FROM node:22-bookworm-slim AS dependencies
WORKDIR /app
COPY package.json package-lock.json ./
COPY apps/web/package.json ./apps/web/package.json
COPY packages/fdc-scripts/package.json ./packages/fdc-scripts/package.json
COPY packages/fcc-extension/typescript/package.json ./packages/fcc-extension/typescript/package.json
RUN npm ci

FROM node:22-bookworm-slim AS build
WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_FLARE_CHAIN_ID=114
ARG NEXT_PUBLIC_FLARE_RPC_URL
ARG NEXT_PUBLIC_AVERLOCK_GUARD_MANAGER
ARG NEXT_PUBLIC_AVERLOCK_INSTRUCTION_SENDER
ARG NEXT_PUBLIC_AVERLOCK_PROTECTION_VAULT
ARG NEXT_PUBLIC_AVERLOCK_PRICE_READER
ARG NEXT_PUBLIC_AVERLOCK_PAYMENT_VERIFIER
ARG NEXT_PUBLIC_AVERLOCK_FTEST_XRP
ARG NEXT_PUBLIC_FLARE_TEE_MANAGER
ARG NEXT_PUBLIC_AVERLOCK_TEE_ID
ARG NEXT_PUBLIC_AVERLOCK_MANAGER_DEPLOYMENT_BLOCK
ARG NEXT_PUBLIC_AVERLOCK_RULE_ID
ARG NEXT_PUBLIC_AVERLOCK_EVENT_HASH
ARG NEXT_PUBLIC_AVERLOCK_ACTION_ID
ARG NEXT_PUBLIC_AVERLOCK_POSITION_ID
ARG NEXT_PUBLIC_AVERLOCK_REGISTRATION_BLOCK
ARG NEXT_PUBLIC_AVERLOCK_EXECUTION_BLOCK
ARG NEXT_PUBLIC_AVERLOCK_XRPL_TRANSACTION
ARG NEXT_PUBLIC_AVERLOCK_FDC_REQUEST_TRANSACTION
ARG NEXT_PUBLIC_AVERLOCK_FDC_VOTING_ROUND
ARG NEXT_PUBLIC_AVERLOCK_XRPL_DESTINATION
ARG NEXT_PUBLIC_AVERLOCK_XRPL_DELIVERED_DROPS

ENV NEXT_PUBLIC_FLARE_CHAIN_ID=$NEXT_PUBLIC_FLARE_CHAIN_ID \
    NEXT_PUBLIC_FLARE_RPC_URL=$NEXT_PUBLIC_FLARE_RPC_URL \
    NEXT_PUBLIC_AVERLOCK_GUARD_MANAGER=$NEXT_PUBLIC_AVERLOCK_GUARD_MANAGER \
    NEXT_PUBLIC_AVERLOCK_INSTRUCTION_SENDER=$NEXT_PUBLIC_AVERLOCK_INSTRUCTION_SENDER \
    NEXT_PUBLIC_AVERLOCK_PROTECTION_VAULT=$NEXT_PUBLIC_AVERLOCK_PROTECTION_VAULT \
    NEXT_PUBLIC_AVERLOCK_PRICE_READER=$NEXT_PUBLIC_AVERLOCK_PRICE_READER \
    NEXT_PUBLIC_AVERLOCK_PAYMENT_VERIFIER=$NEXT_PUBLIC_AVERLOCK_PAYMENT_VERIFIER \
    NEXT_PUBLIC_AVERLOCK_FTEST_XRP=$NEXT_PUBLIC_AVERLOCK_FTEST_XRP \
    NEXT_PUBLIC_FLARE_TEE_MANAGER=$NEXT_PUBLIC_FLARE_TEE_MANAGER \
    NEXT_PUBLIC_AVERLOCK_TEE_ID=$NEXT_PUBLIC_AVERLOCK_TEE_ID \
    NEXT_PUBLIC_AVERLOCK_MANAGER_DEPLOYMENT_BLOCK=$NEXT_PUBLIC_AVERLOCK_MANAGER_DEPLOYMENT_BLOCK \
    NEXT_PUBLIC_AVERLOCK_RULE_ID=$NEXT_PUBLIC_AVERLOCK_RULE_ID \
    NEXT_PUBLIC_AVERLOCK_EVENT_HASH=$NEXT_PUBLIC_AVERLOCK_EVENT_HASH \
    NEXT_PUBLIC_AVERLOCK_ACTION_ID=$NEXT_PUBLIC_AVERLOCK_ACTION_ID \
    NEXT_PUBLIC_AVERLOCK_POSITION_ID=$NEXT_PUBLIC_AVERLOCK_POSITION_ID \
    NEXT_PUBLIC_AVERLOCK_REGISTRATION_BLOCK=$NEXT_PUBLIC_AVERLOCK_REGISTRATION_BLOCK \
    NEXT_PUBLIC_AVERLOCK_EXECUTION_BLOCK=$NEXT_PUBLIC_AVERLOCK_EXECUTION_BLOCK \
    NEXT_PUBLIC_AVERLOCK_XRPL_TRANSACTION=$NEXT_PUBLIC_AVERLOCK_XRPL_TRANSACTION \
    NEXT_PUBLIC_AVERLOCK_FDC_REQUEST_TRANSACTION=$NEXT_PUBLIC_AVERLOCK_FDC_REQUEST_TRANSACTION \
    NEXT_PUBLIC_AVERLOCK_FDC_VOTING_ROUND=$NEXT_PUBLIC_AVERLOCK_FDC_VOTING_ROUND \
    NEXT_PUBLIC_AVERLOCK_XRPL_DESTINATION=$NEXT_PUBLIC_AVERLOCK_XRPL_DESTINATION \
    NEXT_PUBLIC_AVERLOCK_XRPL_DELIVERED_DROPS=$NEXT_PUBLIC_AVERLOCK_XRPL_DELIVERED_DROPS

RUN npm run build

FROM node:22-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production \
    PORT=3000 \
    AVERLOCK_POLICY_HELPER_PATH=/usr/local/bin/policy-app-helper
COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=build /app/package.json /app/package-lock.json ./
COPY --from=build /app/apps/web/package.json ./apps/web/package.json
COPY --from=build /app/apps/web/.next ./apps/web/.next
COPY --from=fcc-helper /out/policy-app-helper /usr/local/bin/policy-app-helper
EXPOSE 3000
CMD ["npm", "run", "start"]
