#!/usr/bin/env bash
# test.sh — Send instructions on-chain, poll for results, and validate correctness.
#
# Run this AFTER post-build.sh (TEE machine must be registered and running).
#
# Inputs (env vars):
#   EXT_PROXY_URL       — extension proxy URL (auto-detected: :6674 for Docker, :6664 for local)
#   CHAIN_URL           — chain RPC URL (default: http://127.0.0.1:8545)
#   ADDRESSES_FILE      — path to deployed-addresses.json (auto-detected if unset)
#   INSTRUCTION_SENDER  — deployed InstructionSender address (from config/extension.env)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Preserve only a TEE expectation explicitly supplied by the caller. Local
# .env files are allowed to configure transport and signing, but must never
# silently replace the live TEE identity. With no explicit value, run-test
# derives the TEE from /info and verifies it against the on-chain PRODUCTION
# registration before sending any instruction.
CALLER_TEE_ID="${TEE_ID:-}"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${GREEN}[test]${NC} $*"; }
step() { echo -e "\n${CYAN}=== Step $1: $2 ===${NC}"; }
die()  { echo -e "${RED}[test] ERROR:${NC} $*" >&2; exit 1; }

# --- Load .env from project root (if present) ---
if [[ -f "$PROJECT_DIR/.env" ]]; then
    set -a
    source "$PROJECT_DIR/.env"
    set +a
fi

# --- Source extension config (generated by pre-build.sh) ---
CONFIG_FILE="$PROJECT_DIR/config/extension.env"
if [[ -f "$CONFIG_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
    log "Loaded config from $CONFIG_FILE"
fi

# Auto-detect proxy port: use Docker port (6674) if ext-proxy container is running,
# otherwise fall back to local Go process port (6664).
if [[ -z "${EXT_PROXY_URL:-}" ]]; then
    if docker compose -f "$PROJECT_DIR/docker-compose.yaml" ps ext-proxy --status running 2>/dev/null | grep -q ext-proxy; then
        EXT_PROXY_URL="http://localhost:6674"
    else
        EXT_PROXY_URL="http://localhost:6664"
    fi
fi
CHAIN_URL="${CHAIN_URL:-http://127.0.0.1:8545}"
RESULT_PROXY_URL="${RESULT_PROXY_URL:-$EXT_PROXY_URL}"
ADDRESSES_FILE="${ADDRESSES_FILE:-}"
# Resolve relative paths against PROJECT_DIR (not caller's cwd)
if [[ -n "$ADDRESSES_FILE" && "$ADDRESSES_FILE" != /* ]]; then
    ADDRESSES_FILE="$PROJECT_DIR/$ADDRESSES_FILE"
fi
INSTRUCTION_SENDER="${INSTRUCTION_SENDER:-}"
TEE_ID="$CALLER_TEE_ID"
EXTENSION_ID="${EXTENSION_ID:-}"

[[ -n "$INSTRUCTION_SENDER" ]] || die "INSTRUCTION_SENDER not set. Run pre-build.sh first or set it manually."
[[ -n "$EXTENSION_ID" ]] || die "EXTENSION_ID not set. Run pre-build.sh first or set it manually."

# --- Auto-detect addresses file ---
LOCAL_MODE="${LOCAL_MODE:-true}"
if [[ -z "$ADDRESSES_FILE" ]]; then
    if [[ "$LOCAL_MODE" != "true" ]]; then
        # Non-local mode: use coston2 deployed addresses
        candidate="$PROJECT_DIR/config/coston2/deployed-addresses.json"
        if [[ -f "$candidate" ]]; then
            ADDRESSES_FILE="$(cd "$(dirname "$candidate")" && pwd)/$(basename "$candidate")"
        fi
    fi

    # Fall back to sim_dump candidates (local devnet)
    if [[ -z "$ADDRESSES_FILE" ]]; then
        for candidate in \
            "$PROJECT_DIR/../../e2e/docker/sim_dump/deployed-addresses.json" \
            "$PROJECT_DIR/../docker/sim_dump/deployed-addresses.json" \
            "$PROJECT_DIR/../../docker/sim_dump/deployed-addresses.json" \
            "$PROJECT_DIR/../../../docker/sim_dump/deployed-addresses.json"; do
            if [[ -f "$candidate" ]]; then
                ADDRESSES_FILE="$(cd "$(dirname "$candidate")" && pwd)/$(basename "$candidate")"
                break
            fi
        done
    fi

    [[ -n "$ADDRESSES_FILE" ]] || die "Cannot find deployed-addresses.json. Set ADDRESSES_FILE."
fi

[[ -f "$ADDRESSES_FILE" ]] || die "Addresses file not found: $ADDRESSES_FILE"

# Resolve to absolute path so it works after cd into tools/
ADDRESSES_FILE="$(cd "$(dirname "$ADDRESSES_FILE")" && pwd)/$(basename "$ADDRESSES_FILE")"

log "Extension proxy:    $EXT_PROXY_URL"
log "Result proxy:       $RESULT_PROXY_URL"
log "Chain URL:          $CHAIN_URL"
log "Addresses file:     $ADDRESSES_FILE"
log "InstructionSender:  $INSTRUCTION_SENDER"

# --- Pre-flight: verify extension proxy is reachable ---
if ! curl -sf -o /dev/null "$EXT_PROXY_URL/info" 2>/dev/null; then
    die "Extension proxy not reachable at $EXT_PROXY_URL. Is Docker Compose running? (docker compose up -d)"
fi
log "Extension proxy is reachable"

# CREATE_POLICY restore is a one-shot encrypted instruction. Never broadcast it
# unless the live TEE, registry selection, signing-policy round, Redis, proxy,
# and empty extension state have passed the deterministic readiness gate.
restore_requested=false
resume_requested=false
retire_requested=false
for argument in "$@"; do
    [[ "$argument" == "-restorePolicyArtifact" || "$argument" == "--restorePolicyArtifact" ]] && restore_requested=true
    [[ "$argument" == "-restoreActionId" || "$argument" == "--restoreActionId" ]] && resume_requested=true
    [[ "$argument" == "-retireStaleTees" || "$argument" == "--retireStaleTees" ]] && retire_requested=true
done
if [[ "$restore_requested" == "true" && "$resume_requested" != "true" && "$retire_requested" != "true" ]]; then
    EXPECTED_TEE_ID="${TEE_ID:-}" EXPECTED_EXTENSION_ID="$EXTENSION_ID" \
        EXPECTED_PROXY_URL="$EXT_PROXY_URL" "$SCRIPT_DIR/fcc-ready-for-instruction.sh"
fi

# --- Run test ---
step 1 "Run extension tests"
cd "$PROJECT_DIR/tools"
go run ./cmd/run-test \
    -a "$ADDRESSES_FILE" \
    -c "$CHAIN_URL" \
    -p "$EXT_PROXY_URL" \
    -resultProxy "$RESULT_PROXY_URL" \
    -instructionSender "$INSTRUCTION_SENDER" \
    -extensionId "$EXTENSION_ID" \
    -tee "$TEE_ID" \
    "$@" \
    || die "Test failed"

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN} Tests passed${NC}"
echo -e "${GREEN}========================================${NC}"
