import { getAddress, stringToHex, type Address, type Hex } from "viem";
import { contracts, coston2, fccConfig } from "./config";

export const prepareGuardEvaluationGasLimit=500_000n;
export function withPrepareGuardEvaluationGasLimit<const T extends object>(request:T){return {...request,gas:prepareGuardEvaluationGasLimit};}

export type FdcPreparation = { payment:{hash:string;destination:string;deliveredDrops:string;validated:true;result:string};ruleId:Hex;abiEncodedRequest:Hex;requestFee:string;fdcHub:Address;knownRequestTransaction?:Hex };
export type PublicProof = readonly [readonly Hex[], readonly [Hex,Hex,bigint,bigint,readonly [Hex,Address],readonly [bigint,bigint,string,Hex,Hex,Hex,bigint,bigint,bigint,bigint,boolean,Hex,boolean,bigint,number]]];
export type VerifiedDecision = { signatureValid:true;actionId:Hex;submissionTag:string;status:number;data:Hex;signature:Hex;resultHash:Hex;tee:Address;extensionId:string;decision:{domain:Hex;ruleId:Hex;eventHash:Hex;triggered:boolean;protectedUsd18:string;protectBps:number;scheduleId:number;eventValueUsd18:string;evaluatedAt:number;nonce:string;resultExpiry:number} };
const json = async (response:Response) => { const value=await response.json(); if(!response.ok) throw new Error(value.error||"Application verification failed."); return value; };
export async function preparePaymentProof(ruleId:Hex,transactionHash:string):Promise<FdcPreparation>{return json(await fetch("/api/averlock/fdc/prepare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ruleId,transactionHash}),cache:"no-store"}));}
export async function retrievePaymentProof(abiEncodedRequest:Hex,requestTransaction:Hex){return json(await fetch("/api/averlock/fdc/proof",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({abiEncodedRequest,requestTransaction}),cache:"no-store"}));}
const bigintFields=new Set(["votingRound","lowestUsedTimestamp","blockNumber","blockTimestamp","spentAmount","intendedSpentAmount","receivedAmount","intendedReceivedAmount","destinationTag"]);
export function hydrateProof(value:unknown):PublicProof { const walk=(item:unknown,key=""):unknown=>Array.isArray(item)?item.map((entry)=>walk(entry)):item&&typeof item==="object"?Object.fromEntries(Object.entries(item as Record<string,unknown>).map(([name,entry])=>[name,walk(entry,name)])):bigintFields.has(key)?BigInt(item as string):item;return walk(value) as PublicProof; }
export function evaluationPayload(ruleId:Hex,eventHash:Hex,nonce:number):Hex{return stringToHex(JSON.stringify({ruleId,eventHash,nonce}));}
export async function waitForEvaluation(actionId:Hex,ruleId:Hex,eventHash:Hex,nonce:number,timeoutMs=120_000):Promise<VerifiedDecision>{const deadline=Date.now()+timeoutMs;const url=`/api/averlock/fcc/evaluation/${actionId}?ruleId=${ruleId}&eventHash=${eventHash}&nonce=${nonce}`;while(Date.now()<deadline){const response=await fetch(url,{cache:"no-store"});const value=await response.json();if(response.ok&&!value.pending)return{...value,signature:canonicalContractSignature(value.signature)};if(response.status!==202)throw new Error(value.error||"FCC evaluation failed closed.");await new Promise((resolve)=>setTimeout(resolve,2000));}throw new Error("The FCC decision is still pending. No execution was attempted.");}
export function exactProtectedTokenUnits(protectedUsd18:bigint,priceUsd18:bigint){if(priceUsd18<=0n)throw new Error("Stored price is invalid.");return protectedUsd18*1_000_000n/priceUsd18;}
export function canonicalContractSignature(signature:Hex):Hex{const bytes=signature.slice(2);if(bytes.length!==130)throw new Error("FCC signature has an invalid length.");const recovery=Number.parseInt(bytes.slice(128),16);if(recovery===0||recovery===1)return `${signature.slice(0,-2)}${(recovery+27).toString(16)}` as Hex;if(recovery===27||recovery===28)return signature;throw new Error("FCC signature has an invalid recovery identifier.");}
export function fdcState(finalized:boolean,proofAvailable:boolean){return !finalized?"waiting-finalization":proofAvailable?"verified":"waiting-proof" as const;}
export function executionPreflight(input:{triggered:boolean;protectedUsd18:bigint;priceUsd18:bigint;balance:bigint;allowance:bigint;expiry:number;now:number;eventConsumed:boolean;resultConsumed:boolean;nonceConsumed:boolean}){if(input.eventConsumed||input.resultConsumed||input.nonceConsumed)throw new Error("Replay state is already consumed.");if(input.expiry<=input.now)throw new Error("FCC result expired.");const amount=input.triggered?exactProtectedTokenUnits(input.protectedUsd18,input.priceUsd18):0n;if(input.balance<amount)throw new Error("Insufficient token balance.");return{amount,approvalRequired:input.allowance<amount,approvalAmount:input.allowance<amount?amount:0n};}
export function requireSuccessfulSimulation(success:boolean){if(!success)throw new Error("Transaction simulation failed.");return true;}
export function paymentStageError(stage:string,error:unknown){const message=error instanceof Error?error.message:"";if(stage==="preflight"||/executeGuard|ECDSAInvalidSignature|0xf645eedf/i.test(message))return "Execution simulation rejected the signed FCC result. No token approval or execution transaction was sent.";if(stage==="fcc-wait")return "FCC result retrieval or signature verification failed. The prepared snapshot remains unchanged.";return "";}
export function freshNonce(){return Date.now()*1000+crypto.getRandomValues(new Uint16Array(1))[0];}
export function currentUnixTime(){return Math.floor(Date.now()/1000);}
export const fdcHubAbi=[{type:"function",name:"requestAttestation",stateMutability:"payable",inputs:[{name:"data",type:"bytes"}],outputs:[]}] as const;
export const instructionFee=fccConfig.instructionFee;
export const executionContracts={manager:contracts.guardManager,token:contracts.ftestXrp,vault:contracts.protectionVault};
export function canProcessPayment(input:{status:"active"|"expired"|"executed";eventHash?:Hex;eventConsumed?:boolean;connectedAddress?:string;owner:string;chainId?:number}){const replayStateSafe=input.eventHash?input.eventConsumed===false:input.eventConsumed!==true;if(input.status!=="active"||!replayStateSafe||input.chainId!==coston2.id||!input.connectedAddress)return false;try{return getAddress(input.connectedAddress)===getAddress(input.owner);}catch{return false;}}
export function paymentFlowContainsPrivateData(value:unknown){const text=JSON.stringify(value,(_,item)=>typeof item==="bigint"?item.toString():item);return ["thresholdUsd18","protectBps","maxPerEventUsd18","cooldownSeconds","expiresAt"].some((key)=>text.includes(key));}
