import { describe, expect, it } from "vitest";
import { keccak256, stringToHex, type Address, type Hex } from "viem";
import { contracts, dashboardSelection } from "./config";
import { withReadTimeout } from "./read-timeout";
import { readVerification, resolveVerificationRule, verifyViewContainsPrivateData } from "./verify";
import type { EvaluationSnapshot, GuardRecord, VaultPosition } from "./types";

const owner = "0x8E4f5D2736B988D4e922b988FF89bcCde45C6f2f" as Address; const ruleId = `0x${"11".repeat(32)}` as Hex; const commitment = `0x${"22".repeat(32)}` as Hex; const receiver = `0x${"33".repeat(32)}` as Hex; const eventHash = `0x${"44".repeat(32)}` as Hex; const actionId = `0x${"55".repeat(32)}` as Hex; const tx = `0x${"66".repeat(32)}` as Hex;
const guard: GuardRecord = { owner, ruleId, policyCommitment: commitment, monitoredReceiverHash: receiver, scheduleId: 1, active: true, createdAt: 100n };
const snapshot: EvaluationSnapshot = { ruleId, eventValueUsd18: 1_000n, priceUsd18: 2n, priceTimestamp: 90n, paymentTimestamp: 80n, preparedAt: 100n };
const position: VaultPosition = { id: 1n, asset: contracts.ftestXrp, beneficiary: owner, totalDeposited: 700_000_000n, claimed: 0n, startTimestamp: 100n, endTimestamp: 200n, createdAt: 100n };
const domain = keccak256(stringToHex("AVERLOCK_GUARD_RESULT_V2"));
function mock(options: { chain?: number; execute?: boolean; commitment?: Hex; action?: Hex; beneficiary?: Address; priceFails?: boolean; priceHangs?: boolean } = {}) { const ranges: [bigint,bigint][] = []; return { ranges, client: { getChainId: async () => options.chain ?? 114, readContract: async ({ functionName }: { functionName: string }) => { if (options.priceHangs && functionName === "getXrpUsdPriceUsd18") return await new Promise<never>(() => undefined); if (options.priceFails && functionName === "getXrpUsdPriceUsd18") throw new Error("optional"); const map: Record<string, unknown> = { getGuard: guard, protectionVault: contracts.protectionVault, paymentVerifier: contracts.paymentVerifier, priceReader: contracts.priceReader, fxrp: contracts.ftestXrp, extensionId: 65_927n, GUARD_RESULT_DOMAIN: domain, getEvaluationSnapshot: snapshot, isEventConsumed: Boolean(options.execute), isResultConsumed: Boolean(options.execute), getPosition: { ...position, beneficiary: options.beneficiary || owner }, claimableAmount: 1n, remainingLockedAmount: 2n, isFullyVested: false, getXrpUsdPriceUsd18: [3n, 110n] }; return map[functionName]; }, getLogs: async ({ event, fromBlock, toBlock }: { event: { name: string }; fromBlock: bigint; toBlock: bigint }) => { ranges.push([fromBlock,toBlock]); if (event.name === "GuardRegistered") return [{ args: { owner, ruleId, policyCommitment: options.commitment || commitment, monitoredReceiverHash: receiver, scheduleId: 1 }, transactionHash: tx }]; if (event.name === "GuardEvaluated") return options.execute ? [{ args: { actionId: options.action || actionId, triggered: true }, transactionHash: tx }] : []; if (event.name === "GuardTriggered") return options.execute ? [{ args: { vaultPositionId: 1n }, transactionHash: tx }] : []; return []; } } }; }
const active = { owner, registrationBlock: 1n }; const executed = { ...active, eventHash, actionId, executionBlock: 2n };

describe("public verification", () => {
  it("verifies a complete executed event", async () => { const { client } = mock({ execute: true }); const data = await readVerification(ruleId, executed, client as never); expect(data.detail.status).toBe("executed"); expect(data.nodes.every((node) => node.state === "verified")).toBe(true); });
  it("shows an active guard as waiting", async () => { const { client } = mock(); const data = await readVerification(ruleId, active, client as never); expect(data.detail.status).toBe("active"); expect(data.nodes.find((node) => node.id === "vault")?.state).toBe("waiting"); });
  it("isolates missing optional market/FDC metadata", async () => { const { client } = mock({ priceFails: true }); const data = await readVerification(ruleId, active, client as never); expect(data.optionalErrors).toContain("Current FTSO price unavailable"); expect(data.detail.guard.ruleId).toBe(ruleId); });
  it("times out optional market metadata instead of hanging verification", async () => { const { client } = mock({ priceHangs: true }); const data = await readVerification(ruleId, active, client as never, 1); expect(data.optionalErrors).toContain("Current FTSO price unavailable"); });
  it("rejects the wrong chain", async () => { const { client } = mock({ chain: 1 }); await expect(readVerification(ruleId, active, client as never)).rejects.toThrow(/Wrong chain/); });
  it("rejects commitment mismatch", async () => { const { client } = mock({ commitment: `0x${"99".repeat(32)}` as Hex }); await expect(readVerification(ruleId, active, client as never)).rejects.toThrow(/binding mismatch/); });
  it("rejects result mismatch", async () => { const { client } = mock({ execute: true, action: `0x${"99".repeat(32)}` as Hex }); await expect(readVerification(ruleId, executed, client as never)).rejects.toThrow(/action binding mismatch/); });
  it("rejects beneficiary mismatch", async () => { const { client } = mock({ execute: true, beneficiary: "0x0000000000000000000000000000000000000001" }); await expect(readVerification(ruleId, executed, client as never)).rejects.toThrow(/beneficiary/); });
  it("never contains private policy data", async () => { const { client } = mock({ execute: true }); const data = await readVerification(ruleId, executed, client as never); expect(verifyViewContainsPrivateData(data)).toBe(false); });
  it("uses only exact receipt blocks", async () => { const { client, ranges } = mock({ execute: true }); await readVerification(ruleId, executed, client as never); expect(ranges.every(([from,to]) => from === to)).toBe(true); });
  it("resolves only known transaction receipts", () => { expect(resolveVerificationRule(tx, [{ ruleId, registrationBlock: "1", transactionHash: tx, owner }])).toBe(ruleId); expect(resolveVerificationRule("999", [])).toBeUndefined(); });
  it("resolves the configured rule, event, and position identifiers", () => { expect(resolveVerificationRule(dashboardSelection.ruleId, [])).toBe(dashboardSelection.ruleId); expect(resolveVerificationRule(dashboardSelection.eventHash, [])).toBe(dashboardSelection.ruleId); expect(resolveVerificationRule(dashboardSelection.positionId.toString(), [])).toBe(dashboardSelection.ruleId); });
  it("bounds a stalled required verification operation", async () => { await expect(withReadTimeout(new Promise<never>(() => undefined), "Required read", 1)).rejects.toThrow(/Required read did not respond/); });
});
