"use client";

import { useEffect, useMemo, useState } from "react";
import { type Hex } from "viem";
import { useAccount, useSwitchChain } from "wagmi";
import { Icon } from "@/components/dashboard/icons";
import { contracts, coston2, dashboardSelection, fccConfig } from "@/lib/averlock/config";
import { compactAddress, formatDate, formatToken, formatUsd18, formatXrpFromSnapshot } from "@/lib/averlock/format";
import { loadGuardIndex } from "@/lib/averlock/guard-index";
import { publicFdcMetadata, readVerification, resolveVerificationRule, verificationAnchor, type VerificationNode, type VerifyData } from "@/lib/averlock/verify";
import { devError, userFacingError } from "@/lib/averlock/errors";

const explorer = coston2.blockExplorers.default.url; const xrplExplorer = "https://testnet.xrpl.org/transactions";
export function VerifyPage() {
  const { address, chainId, isConnected } = useAccount(); const { switchChain } = useSwitchChain();
  const [query, setQuery] = useState<string>(dashboardSelection.ruleId); const [selectedRule, setSelectedRule] = useState<Hex>(dashboardSelection.ruleId); const [data, setData] = useState<VerifyData>(); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [selectedNode, setSelectedNode] = useState<VerificationNode>();
  const entries = useMemo(() => address ? loadGuardIndex(address) : [], [address]);
  useEffect(() => {
    if (isConnected && chainId !== coston2.id) return;
    let cancelled = false;
    void (async () => {
      // Yield once so dependency-driven resets are not synchronous effect updates.
      await Promise.resolve();
      if (cancelled) return;
      setLoading(true); setError(""); setData(undefined);
      try { const value = await readVerification(selectedRule, verificationAnchor(selectedRule, undefined, entries)); if (!cancelled) setData(value); }
      catch (cause) { devError("proof verification", cause); if (!cancelled) setError(userFacingError(cause, "Public proof verification could not be completed safely.")); }
      finally { if (!cancelled) setLoading(false); }
    })();
    return () => { cancelled = true; };
  }, [chainId, entries, isConnected, selectedRule]);
  function inspect(event: React.FormEvent) { event.preventDefault(); const resolved = resolveVerificationRule(query, entries); if (!resolved) { setLoading(false); setData(undefined); setError("No receipt-backed guard matches that rule, event, position, or transaction identifier."); return; } setError(""); setData(undefined); setLoading(true); setSelectedRule(resolved); }
  if (isConnected && chainId !== coston2.id) return <main className="verify-page"><State title="Coston2 required" body="Verification fails closed when the connected wallet is on another chain."><button className="primary-button" onClick={() => switchChain({ chainId: coston2.id })}>Switch to Coston2</button></State></main>;
  return <main className="verify-page"><header className="verify-hero"><div><p className="eyebrow">Public proof inspector</p><h1>Verify AVERLOCK</h1><p>Inspect the public proofs and contract bindings behind a protected event.</p><div className="verify-identity"><span className="network-pill"><span/>Coston2 · 114</span><span><Icon name="wallet"/>{address ? compactAddress(address, 12, 10) : "Wallet not connected"}</span></div></div><span className="verify-hero-shield"><Icon name="shield"/></span></header>
    <form className="verify-search" onSubmit={inspect}><label htmlFor="verify-query">Rule ID, event hash, position ID, or known transaction hash</label><div><input id="verify-query" value={query} onChange={(event) => setQuery(event.target.value)} spellCheck={false}/><button className="primary-button" type="submit">Inspect public state</button></div><small>Discovery is limited to configured and receipt-backed identifiers. No wide block scan is performed.</small></form>
    {error ? <State title="Verification stopped" body={error}/> : loading ? <State title="Reading public proofs" body="Checking Coston2 storage, exact receipts, and cryptographic bindings."/> : data ? <VerificationContent data={data} selected={selectedNode} onSelect={setSelectedNode}/> : <State title="Verification unavailable" body="The public verification read finished without a result."/>}</main>;
}

function VerificationContent({ data, selected, onSelect }: { data: VerifyData; selected?: VerificationNode; onSelect: (node?: VerificationNode) => void }) { const d = data.detail; const fdc = publicFdcMetadata(); return <div className="verify-content">
  <section className="verify-summary"><div><p className="eyebrow">Verification summary</p><h2>{d.status === "executed" ? "Protected event verified" : "Registered guard verified"}</h2><p>{d.status === "executed" ? "The payment proof, stored valuation, signed decision, execution, and vault bindings agree." : "The public guard is valid and waiting for a qualifying verified payment."}</p></div><div className="verify-summary-grid"><Check label="Guard registered" ok/><Check label="Policy commitment" ok/><Check label="FDC proof" ok={Boolean(d.snapshot)} waiting={!d.snapshot}/><Check label="FTSO snapshot" ok={Boolean(d.snapshot)} waiting={!d.snapshot}/><Check label="FCC result" ok={Boolean(d.actionId)} waiting={!d.actionId}/><Check label="Vault position" ok={Boolean(d.position)} waiting={!d.position}/></div></section>
  <section className="verify-graph"><div className="section-heading"><div><p className="eyebrow">Verification graph</p><h2>Public trust path</h2></div><p>Select a node to inspect its verified public state.</p></div><div className="verify-graph-track">{data.nodes.map((node, index) => <div className="verify-graph-segment" key={node.id}><button className={`verify-graph-node ${node.state} ${selected?.id === node.id ? "selected" : ""}`} onClick={() => onSelect(node)} aria-pressed={selected?.id === node.id} aria-label={`Inspect ${node.label}: ${node.state}`}><span><Icon name={node.id === "xrpl" ? "wallet" : node.id === "fdc" ? "proof" : node.id === "ftso" ? "price" : node.id === "fcc" ? "lock" : node.id === "manager" ? "decision" : "vault"}/></span><strong>{node.label}</strong><small>{node.state}</small></button>{index < data.nodes.length - 1 && <span className={`verify-graph-edge ${node.state === "verified" ? "complete" : ""}`}><Icon name="arrow"/></span>}</div>)}</div>{selected && <div className="verify-node-detail"><span className={`verify-dot ${selected.state}`}/><strong>{selected.label}</strong><p>{selected.detail}</p><button onClick={() => onSelect(undefined)} aria-label="Close node detail"><Icon name="close"/></button></div>}</section>
  <div className="verify-section-grid"><Panel title="FDC / XRPL payment" eyebrow="External proof" icon="proof"><Rows rows={[["XRPL transaction", fdc.xrplTransaction || "Not indexed"],["Payment status", d.snapshot ? "Verified by accepted XRPPayment proof" : "Waiting"],["Destination", fdc.xrplDestination || "Not indexed"],["Delivered amount", fdc.deliveredDrops ? `${fdc.deliveredDrops} drops` : "Not indexed"],["Proof owner", contracts.guardManager],["Voting round", fdc.fdcVotingRound || "Not indexed"],["Finalized / FdcVerification", d.snapshot ? "Verified / true" : "Not yet verified"],["FDC request transaction", fdc.fdcRequestTransaction || "Not indexed"]]} links={{ "XRPL transaction": fdc.xrplTransaction ? `${xrplExplorer}/${fdc.xrplTransaction}` : undefined, "FDC request transaction": fdc.fdcRequestTransaction ? `${explorer}/tx/${fdc.fdcRequestTransaction}` : undefined }}/></Panel>
    <Panel title="XRP/USD valuation" eyebrow="FTSO" icon="price"><Rows rows={[["Stored execution snapshot", d.snapshot ? formatUsd18(d.snapshot.priceUsd18) : "Not prepared"],["Snapshot timestamp", d.snapshot ? formatDate(d.snapshot.priceTimestamp) : "Unavailable"],["Event value", d.snapshot ? formatUsd18(d.snapshot.eventValueUsd18) : "Unavailable"],["XRP amount", d.snapshot ? formatXrpFromSnapshot(d.snapshot.eventValueUsd18, d.snapshot.priceUsd18) : "Unavailable"],["Current market price", data.livePriceUsd18 ? formatUsd18(data.livePriceUsd18) : "Unavailable"],["Current price timestamp", data.livePriceTimestamp ? formatDate(data.livePriceTimestamp) : "Unavailable"]]}/><p className="verify-callout">The stored execution snapshot is immutable. Current market price is displayed separately and never substitutes for it.</p></Panel>
    <Panel title="Private FCC decision" eyebrow="Confidential verification" icon="lock"><Rows rows={[["Private policy", "Sealed"],["Public commitment", d.guard.policyCommitment],["Action / result ID", d.actionId || "Not produced"],["Result consumed", d.resultConsumed === undefined ? "Unavailable" : d.resultConsumed ? "Yes" : "No"],["Extension ID", fccConfig.extensionId.toString()],["TEE identity", data.tee?.id || "Unavailable"],["TEE status", data.tee ? "PRODUCTION" : "Unavailable"],["Result domain", d.resultDomain]]}/><div className="privacy-note"><Icon name="lock"/><div><strong>Private policy sealed</strong><p>Plaintext policy terms and TEE-decrypted input are never loaded or displayed.</p></div></div></Panel>
    <Panel title="GuardManager / vault" eyebrow="Execution state" icon="vault"><Rows rows={[["GuardManager", contracts.guardManager],["Rule ID", d.guard.ruleId],["Event hash", d.eventHash || "Not prepared"],["Owner", d.guard.owner],["Receiver hash", d.guard.monitoredReceiverHash],["Schedule ID", d.guard.scheduleId.toString()],["Event consumed", d.eventConsumed === undefined ? "Unavailable" : d.eventConsumed ? "Yes" : "No"],["ProtectionVault", contracts.protectionVault],["Position ID", d.position?.id.toString() || "Not created"],["Beneficiary", d.position?.beneficiary || "Not applicable"],["Principal", d.position ? `${formatToken(d.position.totalDeposited)} FTestXRP` : "Not applicable"],["Claimable / locked", d.position ? `${formatToken(d.claimable || 0n)} / ${formatToken(d.remainingLocked || 0n)} FTestXRP` : "Not applicable"]]} links={{ GuardManager: `${explorer}/address/${contracts.guardManager}`, ProtectionVault: `${explorer}/address/${contracts.protectionVault}` }}/></Panel></div>
  {data.optionalErrors.length > 0 && <div className="activity-warning"><Icon name="pulse"/><p>Optional metadata unavailable: {data.optionalErrors.join(" · ")}. Verified core bindings remain intact.</p></div>}
  </div>; }
function Panel({ title, eyebrow, icon, children }: { title: string; eyebrow: string; icon: string; children: React.ReactNode }) { return <section className="verify-panel"><header><span><Icon name={icon}/></span><div><p className="eyebrow">{eyebrow}</p><h3>{title}</h3></div></header>{children}</section>; }
function Rows({ rows, links = {} }: { rows: [string, string][]; links?: Record<string, string | undefined> }) { return <div className="verify-rows">{rows.map(([label, value]) => <div key={label}><small>{label}</small>{links[label] ? <a href={links[label]} target="_blank" rel="noreferrer">{value}<Icon name="external"/></a> : <strong className={value.startsWith("0x") ? "mono" : ""}>{value}</strong>}</div>)}</div>; }
function Check({ label, ok, waiting }: { label: string; ok?: boolean; waiting?: boolean }) { return <div className={ok ? "ok" : waiting ? "waiting" : "failed"}><Icon name={ok ? "check" : "pulse"}/><span>{label}</span><strong>{ok ? "Verified" : waiting ? "Waiting" : "Failed"}</strong></div>; }
function State({ title, body, children }: { title: string; body: string; children?: React.ReactNode }) { return <div className="activity-empty"><span><Icon name="shield"/></span><h2>{title}</h2><p>{body}</p>{children}</div>; }
