"use client";
import { useState } from "react";
import { getAddress, type Hex } from "viem";
import { useAccount, usePublicClient, useWriteContract } from "wagmi";
import { Icon } from "@/components/dashboard/icons";
import { contracts, coston2 } from "@/lib/averlock/config";
import { erc20Abi, guardManagerAbi, guardTriggeredEvent, instructionSenderAbi, vaultAbi } from "@/lib/averlock/contracts";
import { devError, userFacingError } from "@/lib/averlock/errors";
import { updateGuardIndex } from "@/lib/averlock/guard-index";
import { canProcessPayment, evaluationPayload, exactProtectedTokenUnits, fdcHubAbi, hydrateProof, instructionFee, paymentStageError, preparePaymentProof, retrievePaymentProof, waitForEvaluation, withPrepareGuardEvaluationGasLimit, type FdcPreparation, type VerifiedDecision } from "@/lib/averlock/payment-flow";
import { instructionIdFromReceipt } from "@/lib/averlock/writes";
import type { EvaluationSnapshot, GuardDetailData, VaultPosition } from "@/lib/averlock/types";

type Stage="idle"|"xrpl"|"fdc-request"|"fdc-signature"|"fdc-wait"|"proof"|"prepare-signature"|"snapshot"|"fcc-signature"|"fcc-wait"|"preflight"|"approval-signature"|"execution-signature"|"confirming"|"complete"|"failed";
const labels:Record<Stage,string>={idle:"",xrpl:"Verifying XRPL payment", "fdc-request":"Preparing FDC request","fdc-signature":"Awaiting FDC request signature","fdc-wait":"Waiting for FDC finalization",proof:"Retrieving and verifying FDC proof","prepare-signature":"Awaiting snapshot preparation signature",snapshot:"Verifying stored FTSO snapshot","fcc-signature":"Awaiting private evaluation signature","fcc-wait":"Evaluating sealed protection rule",preflight:"Simulating protection execution","approval-signature":"Approve protected amount","execution-signature":"Activate protection",confirming:"Confirming ProtectionVault position",complete:"Protection activated",failed:"Stopped safely"};
export function ProcessPaymentFlow({data,onReceiptIndexed}:{data:GuardDetailData;onReceiptIndexed?:()=>void}){const{address,chainId}=useAccount();const client=usePublicClient({chainId:coston2.id});const{writeContractAsync}=useWriteContract();const[open,setOpen]=useState(false);const[hash,setHash]=useState("");const[stage,setStage]=useState<Stage>("idle");const[error,setError]=useState("");const[detail,setDetail]=useState("");const busy=!['idle','failed','complete'].includes(stage);
const eligible=canProcessPayment({status:data.status,eventHash:data.eventHash,eventConsumed:data.eventConsumed,connectedAddress:address,owner:data.guard.owner,chainId});
async function pollProof(prepared:FdcPreparation,requestTransaction:Hex){const deadline=Date.now()+12*60_000;while(Date.now()<deadline){const result=await retrievePaymentProof(prepared.abiEncodedRequest,requestTransaction);if(result.finalized&&result.proofAvailable&&result.verified)return result;setStage("fdc-wait");setDetail(result.finalized?"Finalized; waiting for public proof availability.":"Flare validators are finalizing the payment proof.");await new Promise((resolve)=>setTimeout(resolve,5000));}throw new Error("FDC proof is not available yet. The submitted request remains valid.");}
async function run(){if(!address||!client||chainId!==coston2.id||getAddress(address)!==getAddress(data.guard.owner)){setError("Connect the Coston2 wallet that owns this guard.");setStage("failed");return;}try{setError("");setStage("xrpl");setDetail("Checking the XRPL Testnet ledger and guard receiver binding.");const prepared=await preparePaymentProof(data.guard.ruleId,hash.trim());let requestTransaction=prepared.knownRequestTransaction;
if(!requestTransaction){setStage("fdc-request");const simulation=await client.simulateContract({address:prepared.fdcHub,abi:fdcHubAbi,functionName:"requestAttestation",args:[prepared.abiEncodedRequest],value:BigInt(prepared.requestFee),account:address});setStage("fdc-signature");requestTransaction=await writeContractAsync(simulation.request);const receipt=await client.waitForTransactionReceipt({hash:requestTransaction,confirmations:1});if(receipt.status!=="success")throw new Error("FDC request transaction reverted.");updateGuardIndex(address,data.guard.ruleId,{fdcRequestTransaction:requestTransaction});}else setDetail("A matching finalized FDC request is already indexed; no duplicate request will be sent.");
setStage("proof");const proofResult=await pollProof(prepared,requestTransaction);const proof=hydrateProof(proofResult.proof);if(getAddress(proof[1][4][1])!==getAddress(contracts.guardManager))throw new Error("FDC proof owner binding mismatch.");const eventHash=await client.readContract({address:contracts.guardManager,abi:guardManagerAbi,functionName:"deriveEventHash",args:[proofResult.transactionId as Hex,proofResult.receivingAddressHash as Hex,BigInt(proofResult.receivedDrops),BigInt(proofResult.paymentTimestamp)]}) as Hex;updateGuardIndex(address,data.guard.ruleId,{eventHash,fdcRequestTransaction:requestTransaction});if(await client.readContract({address:contracts.guardManager,abi:guardManagerAbi,functionName:"isEventConsumed",args:[eventHash]}))throw new Error("This XRP payment has already been processed.");
let snapshot:EvaluationSnapshot|undefined;try{snapshot=await client.readContract({address:contracts.guardManager,abi:guardManagerAbi,functionName:"getEvaluationSnapshot",args:[eventHash]}) as EvaluationSnapshot;}catch{snapshot=undefined;}if(!snapshot){const simulation=await client.simulateContract(withPrepareGuardEvaluationGasLimit({address:contracts.guardManager,abi:guardManagerAbi,functionName:"prepareGuardEvaluation",args:[data.guard.ruleId,proof],account:address}));setStage("prepare-signature");const tx=await writeContractAsync(simulation.request);const receipt=await client.waitForTransactionReceipt({hash:tx,confirmations:1});if(receipt.status!=="success")throw new Error("Snapshot preparation reverted.");updateGuardIndex(address,data.guard.ruleId,{eventHash,preparationTransaction:tx});}
setStage("snapshot");snapshot=await client.readContract({address:contracts.guardManager,abi:guardManagerAbi,functionName:"getEvaluationSnapshot",args:[eventHash]}) as EvaluationSnapshot;if(snapshot.ruleId.toLowerCase()!==data.guard.ruleId.toLowerCase()||snapshot.eventValueUsd18<=0n||snapshot.priceUsd18<=0n)throw new Error("Stored snapshot binding mismatch.");
// The nonce is created only inside this explicit user action, never during render.
// eslint-disable-next-line react-hooks/purity
const nonce=Date.now()*1000+crypto.getRandomValues(new Uint16Array(1))[0];const evaluation=evaluationPayload(data.guard.ruleId,eventHash,nonce);const fccSimulation=await client.simulateContract({address:contracts.instructionSender,abi:instructionSenderAbi,functionName:"evaluateGuard",args:[evaluation],value:instructionFee,account:address});setStage("fcc-signature");const fccTx=await writeContractAsync(fccSimulation.request);const fccReceipt=await client.waitForTransactionReceipt({hash:fccTx,confirmations:1});if(fccReceipt.status!=="success")throw new Error("FCC instruction reverted.");const actionId=instructionIdFromReceipt(fccReceipt);updateGuardIndex(address,data.guard.ruleId,{eventHash,fccTransaction:fccTx,actionId});setStage("fcc-wait");const result=await waitForEvaluation(actionId,data.guard.ruleId,eventHash,nonce);await finish(result,snapshot,eventHash,nonce);
}catch(cause){devError("payment processing",cause);setError(paymentStageError(stage,cause)||userFacingError(cause,"The payment could not be processed safely."));setStage("failed");}}
async function finish(result:VerifiedDecision,snapshot:EvaluationSnapshot,eventHash:Hex,nonce:number){if(!address||!client)return;const now=Math.floor(Date.now()/1000);if(!result.signatureValid||result.decision.eventValueUsd18!==snapshot.eventValueUsd18.toString()||result.decision.resultExpiry<=now)throw new Error("FCC result is expired or does not match the snapshot.");if(await client.readContract({address:contracts.guardManager,abi:guardManagerAbi,functionName:"isResultConsumed",args:[result.actionId]})||await client.readContract({address:contracts.guardManager,abi:guardManagerAbi,functionName:"isNonceUsed",args:[data.guard.ruleId,BigInt(nonce)]}))throw new Error("FCC result or nonce has already been consumed.");const amount=result.decision.triggered?exactProtectedTokenUnits(BigInt(result.decision.protectedUsd18),snapshot.priceUsd18):0n;const[balance,allowance]=await Promise.all([client.readContract({address:contracts.ftestXrp,abi:erc20Abi,functionName:"balanceOf",args:[address]}),client.readContract({address:contracts.ftestXrp,abi:erc20Abi,functionName:"allowance",args:[address,contracts.guardManager]})]);if(balance<amount)throw new Error("Insufficient FTestXRP balance for the protected amount.");const actionResult={actionId:result.actionId,submissionTag:result.submissionTag,status:result.status,data:result.data,signature:result.signature};setStage("preflight");if(allowance<amount){await client.simulateContract({address:contracts.ftestXrp,abi:erc20Abi,functionName:"approve",args:[contracts.guardManager,amount],account:address});setStage("approval-signature");const approval=await writeContractAsync({chainId:coston2.id,address:contracts.ftestXrp,abi:erc20Abi,functionName:"approve",args:[contracts.guardManager,amount]});const receipt=await client.waitForTransactionReceipt({hash:approval,confirmations:1});if(receipt.status!=="success")throw new Error("Token approval reverted.");}
const simulation=await client.simulateContract({address:contracts.guardManager,abi:guardManagerAbi,functionName:"executeGuard",args:[data.guard.ruleId,eventHash,actionResult],account:address});setStage("execution-signature");const execution=await writeContractAsync(simulation.request);setStage("confirming");const receipt=await client.waitForTransactionReceipt({hash:execution,confirmations:1});if(receipt.status!=="success")throw new Error("Guard execution reverted.");updateGuardIndex(address,data.guard.ruleId,{eventHash,actionId:result.actionId,executionTransaction:execution,executionBlock:receipt.blockNumber.toString()});const[eventConsumed,resultConsumed,nonceConsumed,residue,triggers]=await Promise.all([client.readContract({address:contracts.guardManager,abi:guardManagerAbi,functionName:"isEventConsumed",args:[eventHash]}),client.readContract({address:contracts.guardManager,abi:guardManagerAbi,functionName:"isResultConsumed",args:[result.actionId]}),client.readContract({address:contracts.guardManager,abi:guardManagerAbi,functionName:"isNonceUsed",args:[data.guard.ruleId,BigInt(nonce)]}),client.readContract({address:contracts.ftestXrp,abi:erc20Abi,functionName:"balanceOf",args:[contracts.guardManager]}),client.getLogs({address:contracts.guardManager,event:guardTriggeredEvent,args:{owner:address,ruleId:data.guard.ruleId,eventHash},fromBlock:receipt.blockNumber,toBlock:receipt.blockNumber})]);if(!eventConsumed||!resultConsumed||!nonceConsumed||residue!==0n)throw new Error("Post-execution replay or residue verification failed.");const trigger=triggers[0];if(result.decision.triggered&&!trigger)throw new Error("GuardTriggered receipt is missing.");if(trigger){const position=await client.readContract({address:contracts.protectionVault,abi:vaultAbi,functionName:"getPosition",args:[trigger.args.vaultPositionId!]}) as VaultPosition;if(getAddress(position.beneficiary)!==getAddress(address)||position.totalDeposited!==amount)throw new Error("ProtectionVault beneficiary or principal mismatch.");updateGuardIndex(address,data.guard.ruleId,{positionId:position.id.toString()});}
setStage("complete");setDetail(result.decision.triggered?`ProtectionVault position #${trigger?.args.vaultPositionId} created with exact protected principal.`:"The verified event did not trigger the sealed policy and is now replay-protected.");setTimeout(()=>onReceiptIndexed?.(),1800);}
if(!eligible)return null;
return <><div className="process-payment-action"><div><strong>Payment ready to verify?</strong><p>Process a validated XRPL Testnet payment through FDC, FTSO, and the sealed FCC policy.</p></div><button className="primary-button process-payment-button" onClick={()=>setOpen(true)}><Icon name="pulse"/>Process XRP Payment</button></div>{open&&<div className="payment-modal-scrim" role="presentation"><section className="payment-modal" role="dialog" aria-modal="true" aria-labelledby="payment-title"><header><div><p className="eyebrow">Verified payment flow</p><h2 id="payment-title">Process XRP Payment</h2></div><button onClick={()=>!busy&&setOpen(false)} aria-label="Close payment flow" disabled={busy}><Icon name="close"/></button></header><p className="payment-intro">Enter a validated XRPL Testnet transaction. AVERLOCK independently verifies it before any wallet request.</p><label className="form-field"><span>XRPL transaction hash</span><input value={hash} onChange={(event)=>setHash(event.target.value)} disabled={busy} placeholder="64-character XRPL transaction hash" autoComplete="off" spellCheck={false}/></label>{stage!=="idle"&&<div className={`payment-stage ${stage}`} role="status"><span>{stage==="complete"?<Icon name="check"/>:<Icon name="pulse"/>}</span><div><strong>{labels[stage]}</strong><p>{error||detail}</p></div></div>}<div className="payment-privacy"><Icon name="lock"/><p>The browser submits only the rule ID, event hash, and fresh nonce to FCC. It never sends policy terms or an event value.</p></div><footer><button className="secondary-button" onClick={()=>setOpen(false)} disabled={busy}>Cancel</button><button className="primary-button" onClick={run} disabled={busy||!/^[A-Fa-f0-9]{64}$/.test(hash)}>{stage==="failed"?"Retry safely":"Verify and process"}</button></footer></section></div>}</>}
